                <div id="navbar">
                    <ul id='links-1'>
                        <li>
                            <a href="index.php">Home</a>
                        </li>
                        <li>
                            <a href="page.php?page=about_us">About Us</a>
                        </li>
                        <li>
                            <a href="page.php?page=portfolio">Portfolio</a>
                        </li>
                        <li>
                            <a href="page.php?page=contact_us">Contact Us</a>
                        </li>
                    </ul>
                    <ul id='links-2'>
                        <li>
                            <a href="page.php?page=development">Development</a>
                        </li>
                        <li>
                            <a href="page.php?page=open_source">Open Source</a>
                        </li>
                        <li>
                            <a href="page.php?page=services">Services</a>
                        </li>
                        <li>
                            <a href="page.php?page=research">Research</a>
                        </li>
                        <li>
                            <a href="page.php?page=web_design">Web Design</a>
                        </li>
                    </ul>
                </div>
